### ISSUE TITLE
Style leaks from the components

### ISSUE THREAD

**Issue by dlin-me** [butopen/web-components-tailwind-starter-kit#1]
Hi, appreciate your repo. But styles are leaking into the parent page with your approach. 

To show the problem.  Add one <p> to the index.html:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BrowserBot web components</title>
</head>
<body>
<test-component name="Pippo"></test-component>
<test2-component name="Pluto"></test2-component>
<script type="module" src="src/test/test.component.ts"></script>
<script type="module" src="src/test2/test2.component.ts"></script>
<p>This should not be affected, it is</p>
</body>
</html>
```

The result
![image](https://user-images.githubusercontent.com/1905715/207604729-0c5d69e2-d83c-4bc2-871f-af69ada340d4.png)

Also, the styles should not be added to the parent html page header. It should be scoped to the components itself. 

The problem is that the static style variable needs to be the static property of the web component class itself, not to the parent class.

**Comment by salvatoreromeo** [comment]
hi @dlin-me , thanks for posting it. I just fixed it as described below:

this behavior depends on how vite handles style imports: by default, vite adds imported styles into the head.
to ensure that they are not inserted in the head and solve the problem that you mentioned just add `?inline ` in the import of the .scss file

so, for instance:

```typescript
import style from "./test2.component.scss?inline"; // look at the ?inline at the end: it fixes the issue
```


I just updated the repo too ;-)

![image](https://user-images.githubusercontent.com/6431807/207667447-43b78ec9-7caf-4d7e-8ae4-5f99f04fca35.png)

**Comment by dlin-me** [comment]
@salvatoreromeo  Thank you!   This solves the problem.
